[project.urls]
GitHub = "https://github.com/BrokenSource/umidi/"

[project]
name            = "umidi"
description     = "ğŸ¹ Fastest Python MIDI file reading"
authors         = [{name="Tremeschin", email="29046864+Tremeschin@users.noreply.github.com"}]
version         = "0.1.0"
readme          = "readme.md"
requires-python = ">=3.10"
dependencies    = [
    "attrs~=25.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["umidi"]
